input: meshes 

meshes:
	cd src; make

clean:
	rm -f *.vtu *.stat *~*~ *.html *.pyc *.pkl 

clean_all:
	rm -f *.vtu *.stat *~*~ *.html *.pyc adjoint_B.swml adjoint_C.swml adjoint_D.swml adjoint_E.swml optimiser_B.oml optimiser_C.oml optimiser_D.oml optimiser_E.oml
	cd src; rm *ele *node *bound *~*~
