input: clean
	../../bin/gmsh2triangle --2d src/square.msh

clean:
	rm -rf  *.ele *.edge *.node *.poly *.halo *.vtu *.pvtu fluidity.* *.s *.d.1 *.stat \
	matrixdump matrixdump.info heat_* *flredecomp*
