input:
	#../../bin/create_aligned_mesh 1 1 1 5 5 5

clean:
	rm -f *.vtu *.log-? *.err-? *periodised* MMS_B_periodic.ele MMS_B_periodic.face MMS_B_periodic.node periodic_adaptivity_3d.stat \
	matrixdump matrixdump.info
