input: clean
	cp src/square.msh .

clean:
	rm -rf *.halo *.stat *.vtu *.pvtu *.node *.ele *.edge *.log-0 *.err-0 *checkpoint *.convergence
	rm -f *.err-? *.log-?
	rm -rf 5material-droplet_? 5material-droplet_?? \
	matrixdump matrixdump.info
	rm -rf *flredecomp*
