input: clean
	tar -xzvf ../sw_common/sphere.tgz

clean:
	rm -f *.d.* *.vtu
	rm -f fluidity.err-0 fluidity.log-0
	rm -f channel*.ele channel*.face chanel*.node channel*.edge *.stat *.halo
	rm -f *.msh *.geo
