input:
	interval --dx=0.1 --3d 0 1.0 mesh_A
	interval --dx=0.05 --3d 0 1.0 mesh_B
	interval --dx=0.025 --3d 0 1.0 mesh_C
	interval --dx=0.0125 --3d 0 1.0 mesh_D
	interval --dx=0.00625 --3d 0 1.0 mesh_E
