// ************************************************************************* //
//  File: BinnerEnginePluginInfo.C
// ************************************************************************* //

#include <BinnerPluginInfo.h>
#include <avtBinnerFilter.h>

#if defined(__APPLE__)
#define GetEngineInfo Binner_GetEngineInfo
#endif

// ****************************************************************************
//  Function:  GetEngineInfo
//
//  Purpose:
//    Return a new EnginePluginInfo for the Binner operator.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 30 12:05:26 PDT 2006
//
// ****************************************************************************
extern "C" EngineOperatorPluginInfo* GetEngineInfo()
{
    return new BinnerEnginePluginInfo;
}

// ****************************************************************************
//  Method: BinnerEnginePluginInfo::AllocAvtPluginFilter
//
//  Purpose:
//    Return a pointer to a newly allocated avtPluginFilter.
//
//  Returns:    A pointer to the newly allocated avtPluginFilter.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 30 12:05:26 PDT 2006
//
// ****************************************************************************

avtPluginFilter *
BinnerEnginePluginInfo::AllocAvtPluginFilter()
{
    return new avtBinnerFilter;
}
