// ************************************************************************* //
//  File: BinnerCommonPluginInfo.C
// ************************************************************************* //

#include <BinnerPluginInfo.h>
#include <BinnerFilter.h>

// ****************************************************************************
//  Method: BinnerCommonPluginInfo::AllocAttributes
//
//  Purpose:
//    Return a pointer to a newly allocated attribute subject.
//
//  Returns:    A pointer to the newly allocated attribute subject.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 30 12:05:26 PDT 2006
//
// ****************************************************************************

AttributeSubject *
BinnerCommonPluginInfo::AllocAttributes()
{
    return new Binner;
}

// ****************************************************************************
//  Method: BinnerCommonPluginInfo::CopyAttributes
//
//  Purpose:
//    Copy a Binner attribute subject.
//
//  Arguments:
//    to        The destination attribute subject.
//    from      The source attribute subject.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 30 12:05:26 PDT 2006
//
// ****************************************************************************

void 
BinnerCommonPluginInfo::CopyAttributes(AttributeSubject *to,
    AttributeSubject *from)
{
    *((Binner *) to) = *((Binner *) from);
}
