input: default
default: clean
	../../bin/create_aligned_mesh column 1 1 -- -40 1 1 40
clean: 
	rm -rf *.msh *.halo *.vtu *.pvtu *.log* *.err* *.stat blob_[012] *.detectors *.dat *.ele *.node *.bound *.face
