input:	clean
	cp src/MMS_A.msh .
	cp src/MMS_B.msh .
	cp src/MMS_C.msh .
	cp src/MMS_D.msh .

clean:
	rm -f *.vtu *.stat *.log *.node *.ele *.edge *.msh *checkpoint*
	rm -f *.msh
	rm -f matrixdump*
	rm -f fluidity.*
