input:
	../../../scripts/interval --dx=0.025 0 1.0 mesh_A
	../../../scripts/interval --dx=0.0125 0 1.0 mesh_B
	../../../scripts/interval --dx=0.00625 0 1.0 mesh_C
	../../../scripts/interval --dx=0.0030625 0 1.0 mesh_D
	../../../scripts/interval --dx=0.00153125 0 1.0 mesh_E
