#!/usr/bin/env python3
from optparse import OptionParser
import sys

#####################################################################
# Script starts here.
optparser=OptionParser(usage='usage: %prog [options] <layers> <width>',
                       add_help_option=True,
                       description="""Generate the mesh files for a given"""+
		       """number of layers and width.""")

(options, argv) = optparser.parse_args()

#try:
layers=float(argv[0])
width=float(argv[1])
dx = 1.0/layers
print('dx = ',dx)
#except:
#    optparser.print_help()
#    sys.exit(1)

sys.path.append(".")

import makebox

makebox.generate_meshfile("box",layers,width)
