// ************************************************************************* //
//  File: H5PartRandomSamplePluginInfo.C
// ************************************************************************* //

#include <H5PartRandomSamplePluginInfo.h>
#include <H5PartRandomSampleAttributes.h>

#include <visit-config.h>
#if defined(__APPLE__)
extern "C" const char *H5PartRandomSampleVisItPluginVersion = VERSION;
#else
extern "C" const char *VisItPluginVersion = VERSION;
#endif

#if defined(__APPLE__)
#define GetGeneralInfo H5PartRandomSample_GetGeneralInfo
#endif

// ****************************************************************************
//  Function:  GetGeneralInfo
//
//  Purpose:
//    Return a new GeneralPluginInfo for the H5PartRandomSample operator.
//
//  Programmer:  cristina -- generated by xml2info
//  Creation:    Thu Mar 16 10:26:55 PDT 2006
//
// ****************************************************************************
extern "C" GeneralOperatorPluginInfo* GetGeneralInfo()
{
    return new H5PartRandomSampleGeneralPluginInfo;
}

// ****************************************************************************
//  Method: H5PartRandomSampleGeneralPluginInfo::GetName
//
//  Purpose:
//    Return the name of the operator plugin.
//
//  Returns:    A pointer to the name of the operator plugin.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:26:55 PDT 2006
//
// ****************************************************************************

char *
H5PartRandomSampleGeneralPluginInfo::GetName() const
{
    return "H5PartRandomSample";
}

// ****************************************************************************
//  Method: H5PartRandomSampleGeneralPluginInfo::GetVersion
//
//  Purpose:
//    Return the version of the operator plugin.
//
//  Returns:    A pointer to the version of the operator plugin.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:26:55 PDT 2006
//
// ****************************************************************************

char *
H5PartRandomSampleGeneralPluginInfo::GetVersion() const
{
    return "1.0";
}

// ****************************************************************************
//  Method: H5PartRandomSampleGeneralPluginInfo::GetID
//
//  Purpose:
//    Return the id of the operator plugin.
//
//  Returns:    A pointer to the id of the operator plugin.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:26:55 PDT 2006
//
// ****************************************************************************

char *
H5PartRandomSampleGeneralPluginInfo::GetID() const
{
    return "H5PartRandomSample_1.0";
}
// ****************************************************************************
//  Method: H5PartRandomSampleGeneralPluginInfo::EnabledByDefault
//
//  Purpose:
//    Return true if this plugin should be enabled by default; false otherwise.
//
//  Returns:    true/false
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:26:55 PDT 2006
//
// ****************************************************************************

bool
H5PartRandomSampleGeneralPluginInfo::EnabledByDefault() const
{
    return true;
}
