// ************************************************************************* //
//  File: H5PartRandomSampleCommonPluginInfo.C
// ************************************************************************* //

#include <H5PartRandomSamplePluginInfo.h>
#include <H5PartRandomSampleAttributes.h>

// ****************************************************************************
//  Method: H5PartRandomSampleCommonPluginInfo::AllocAttributes
//
//  Purpose:
//    Return a pointer to a newly allocated attribute subject.
//
//  Returns:    A pointer to the newly allocated attribute subject.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:26:55 PDT 2006
//
// ****************************************************************************

AttributeSubject *
H5PartRandomSampleCommonPluginInfo::AllocAttributes()
{
    return new H5PartRandomSampleAttributes;
}

// ****************************************************************************
//  Method: H5PartRandomSampleCommonPluginInfo::CopyAttributes
//
//  Purpose:
//    Copy a H5PartRandomSample attribute subject.
//
//  Arguments:
//    to        The destination attribute subject.
//    from      The source attribute subject.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:26:55 PDT 2006
//
// ****************************************************************************

void 
H5PartRandomSampleCommonPluginInfo::CopyAttributes(AttributeSubject *to,
    AttributeSubject *from)
{
    *((H5PartRandomSampleAttributes *) to) = *((H5PartRandomSampleAttributes *) from);
}
