// ************************************************************************* //
//  File: H5PartRandomSampleGUIPluginInfo.C
// ************************************************************************* //

#include <H5PartRandomSamplePluginInfo.h>
#include <H5PartRandomSampleAttributes.h>
#include <QvisH5PartRandomSampleWindow.h>

#if defined(__APPLE__)
#define GetGUIInfo H5PartRandomSample_GetGUIInfo
#endif

// ****************************************************************************
//  Function:  GetGUIInfo
//
//  Purpose:
//    Return a new GUIPluginInfo for the H5PartRandomSample operator.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:29:14 PDT 2006
//
// ****************************************************************************
extern "C" GUIOperatorPluginInfo* GetGUIInfo()
{
    return new H5PartRandomSampleGUIPluginInfo;
}

// ****************************************************************************
//  Method: H5PartRandomSampleGUIPluginInfo::GetMenuName
//
//  Purpose:
//    Return a pointer to the name to use in the GUI menu.
//
//  Returns:    A pointer to the name to use in the GUI menu.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:29:14 PDT 2006
//
// ****************************************************************************

const char *
H5PartRandomSampleGUIPluginInfo::GetMenuName() const
{
    return "H5PartRandomSample";
}


// ****************************************************************************
//  Method: H5PartRandomSampleGUIPluginInfo::CreatePluginWindow
//
//  Purpose:
//    Return a pointer to an operator's attribute window.
//
//  Arguments:
//    type      The type of the operator.
//    attr      The attribute subject for the operator.
//    notepad   The notepad to use for posting the window.
//
//  Returns:    A pointer to the operator's attribute window.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:29:14 PDT 2006
//
// ****************************************************************************

QvisPostableWindowObserver *
H5PartRandomSampleGUIPluginInfo::CreatePluginWindow(int type, AttributeSubject *attr,
    QvisNotepadArea *notepad)
{
    return new QvisH5PartRandomSampleWindow(type, (H5PartRandomSampleAttributes *)attr,
        "H5PartRandomSample operator attributes", "H5PartRandomSample operator", notepad);
}

// ****************************************************************************
//  Method: H5PartRandomSampleGUIPluginInfo::XPMIconData
//
//  Purpose:
//    Return a pointer to the icon data.
//
//  Returns:    A pointer to the icon data.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:29:14 PDT 2006
//
// ****************************************************************************

#include <icon.xpm>
const char **
H5PartRandomSampleGUIPluginInfo::XPMIconData() const
{
    return icon_xpm;
}
