#!/bin/bash

for F in A B
do
    echo creating set $F

    cp MMS_X.flml MMS_$F.flml 
    sed s/MMS_X/MMS_$F/ MMS_$F.flml > MMS_$F.flml.cp
done

echo setting flml timestep values

sed s/999.9/0.005/ MMS_A.flml.cp > MMS_A.flml
rm MMS_A.flml.cp
sed s/999.9/0.0025/ MMS_B.flml.cp > MMS_B.flml
rm MMS_B.flml.cp
