input: 	clean
	gmsh -3 src/cube.geo -algo front3d -o cube.msh

clean:
	rm -rf fluidity.* cube.msh refinep* refine_* refine.stat adapted_state* metric_input* gradation_metric* bounding_box* adapted_quality*
	rm -rf matrixdump*
