input:	clean
	../../bin/interval --dx=50 --reverse --region_ids='regions.py' -- -350 15000 tank

clean:
	rm -f *.vtu *.stat *.log-0 *.err-0 *.node *.ele *.bound *.edge *_checkpoint* *.convergence *.detectors* matrixdump*
