FROM fluidity/baseimages:impish

USER root

RUN apt-get -y update && \
    apt-get -y dist-upgrade && \
    apt-get -y install python3-pip python3-build python3-junit.xml python3-venv && \
    rm -rf /var/cache/apt/archives && \
    rm -rf /var/lib/apt/lists

COPY . /home/fluidity
RUN chown -R fluidity /home/fluidity

USER fluidity

RUN python3 -m pip install assess

cmake -G Ninja .
ninja
ninja manual
