input: clean
	cp src/sloshing_tank_mesh1.msh .

clean:
	rm -rf *.err-? *.log-? *.d.* *.s* *.vtu *.log sloshing_tank_mesh1.node sloshing_tank_mesh1.ele sloshing_tank_mesh1.face *.detectors \
	matrixdump matrixdump.info
