input:	clean
	../../scripts/gmsh2triangle --2d src/MMS_A.msh
	../../scripts/gmsh2triangle --2d src/MMS_B.msh
	../../scripts/gmsh2triangle --2d src/MMS_C.msh
	../../scripts/gmsh2triangle --2d src/MMS_D.msh
	../../scripts/gmsh2triangle --2d src/MMS_E.msh

clean:
	rm -f *.vtu *.stat *.log* *.err* *.node *.ele *.edge *checkpoint* *.convergence
