input:	clean
	cp src/MMS_A.msh .
	cp src/MMS_B.msh .
	cp src/MMS_C.msh .
	cp src/MMS_D.msh .
	cp src/MMS_E.msh .

clean:
	rm -f *.vtu *.stat *.log* *.err* *.node *.ele *.edge *.msh *checkpoint* *.convergence matrixdump*
