input: default
default: clean
	../../bin/interval --variable_dx=spacing.py --reverse -- -500 0 line
clean: 
	rm -rf *.msh *.halo *.vtu *.pvtu *.log* *.err* *.stat *.detectors *.dat *.ele *.node *.bound
