PROJECT = channel

input: clean

clean:
	rm -f $(PROJECT) $(PROJECT)0 $(PROJECT).fld
	rm -f $(PROJECT).s $(PROJECT).stat
	rm -f *.d.* *.vtu
	rm -f fluidity.err-0 fluidity.log-0
	rm -f *.ele *.face *.node *.edge *.stat *.halo
	rm -f *.msh *.geo
	rm -f *.err-? *.log-? \
	matrixdump matrixdump.info
