#!/usr/bin/env python3
import matplotlib.pyplot as plt
import vtktools
from matplotlib.transforms import Bbox

vtu = vtktools.vtu("cg_80.vtu")
x = [coord[0] for coord in vtu.GetLocations()]
t = vtu.GetScalarField("Tracer")
plt.plot(x, t, "k")
plt.gcf().set_figwidth(4)
plt.gcf().set_figheight(3)
plt.xlim(x[0], x[-1])
plt.ylim(-0.2, 1.2)
plt.xlabel("$x$")
plt.ylabel("$T$")
plt.savefig("cg.pdf", bbox_inches=Bbox([[-0.2, -0.2], [4.0, 3.0]]))
plt.savefig("cg.png", bbox_inches=Bbox([[-0.2, -0.2], [4.0, 3.0]]))
plt.clf()

vtu = vtktools.vtu("supg_80.vtu")
x = [coord[0] for coord in vtu.GetLocations()]
t = vtu.GetScalarField("Tracer")
plt.plot(x, t, "k")
plt.gcf().set_figwidth(4)
plt.gcf().set_figheight(3)
plt.xlim(x[0], x[-1])
plt.ylim(-0.2, 1.2)
plt.xlabel("$x$")
plt.ylabel("$T$")
plt.savefig("supg.pdf", bbox_inches=Bbox([[-0.2, -0.2], [4.0, 3.0]]))
plt.savefig("supg.png", bbox_inches=Bbox([[-0.2, -0.2], [4.0, 3.0]]))
plt.clf()

vtu = vtktools.vtu("su_80.vtu")
x = [coord[0] for coord in vtu.GetLocations()]
t = vtu.GetScalarField("Tracer")
plt.plot(x, t, "k")
plt.gcf().set_figwidth(4)
plt.gcf().set_figheight(3)
plt.xlim(x[0], x[-1])
plt.ylim(-0.2, 1.2)
plt.xlabel("$x$")
plt.ylabel("$T$")
plt.savefig("su.pdf", bbox_inches=Bbox([[-0.2, -0.2], [4.0, 3.0]]))
plt.savefig("su.png", bbox_inches=Bbox([[-0.2, -0.2], [4.0, 3.0]]))
plt.clf()
