#!/usr/bin/env python3
import sys
from optparse import OptionParser

import driven_cavity

#####################################################################
# Script starts here.
optparser = OptionParser(
    usage="usage: %prog [options] <NN>",
    add_help_option=True,
    description="""Generate the mesh files for a given resolution.""",
)

(options, argv) = optparser.parse_args()

try:
    NN = int(argv[0])
except Exception:
    optparser.print_help()
    sys.exit(1)

sys.path.append(".")

driven_cavity.generate_meshfile("driven_cavity", NN)
