#!/usr/bin/env python3
import sys

import driven_cavity
import numpy
import pylab


def usage():
    print(
        """plot_data <NN>

    <NN> is a space-separated list of the inverse mesh spacing."""
    )


try:
    NN = numpy.array(map(int, sys.argv[1:]))
except Exception:
    usage()
    sys.exit(1)

if len(NN) == 0:
    usage()
    sys.exit(1)

error = driven_cavity.retrieve_results(NN)

driven_cavity.plot_results(NN, error)

pylab.show()
