input:
	gmsh -2 src/MMS_B.geo -o MMS_B.msh

clean:
	rm -rf periodic_adaptivity_* *.vtu *.log-? *.err-? *.msh *.edge *.ele *.node periodic_adaptivity.stat periodic_adaptivity_periodised.flml periodic_adaptivity_periodised_parallel.flml *.pvtu \
	matrixdump matrixdump.info
