#!/usr/bin/env python
from optparse import OptionParser
import sys

#####################################################################
# Script starts here.
optparser=OptionParser(usage='usage: %prog [options] <layers>',
                       add_help_option=True,
                       description="""Generate the mesh files for a given"""+
		       """number of layers of elements in the channel.""")

(options, argv) = optparser.parse_args()

try:
    layers=int(argv[0])
except:
    optparser.print_help()
    sys.exit(1)

sys.path.append(".")

import channel_viscous

channel_viscous.generate_meshfile("channel",layers)
