#!/bin/bash
#
# Launch script for diamond

# export the location of a few files
export GDK_PIXBUF_MODULE_FILE="/Applications/Diamond.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
export PANGO_RC_FILE="/Applications/Diamond.app/Contents/Resources/pango_rc"
export DIAMOND_CONFIG_PATH="/Applications/Diamond.app/Contents/Resources"
# run diamond
/Applications/Diamond.app/Contents/bin/python /Applications/Diamond.app/Contents/bin/diamond
