input: clean
	gmsh -2 -o square-periodic-12.msh src/square-periodic_12.geo
	gmsh -2 -o square-periodic-24.msh src/square-periodic_24.geo
	gmsh -2 -o square-periodic-48.msh src/square-periodic_48.geo

clean:
	rm -f *.msh
