input: meshes clean

meshes:
	cd src; make

clean:
	rm -f *.vtu *.stat *~*~ *.html *.pyc *.pkl 

clean_all:
	rm -f *.vtu *.stat *~*~ *.html *.pyc adjoint_B.swml adjoint_C.swml adjoint_D.swml adjoint_E.swml *.pkl
	cd src; rm *ele *node *bound *~*~
