input: clean
	cp src/square.msh .

clean:
	rm -f  *.ele *.edge *.node *.poly *.halo *.vtu *.pvtu fluidity.* *.s *.d.1 *.stat *detectors*
	rm -rf heat_? \
	matrixdump matrixdump.info
	rm -rf *flredecomp*
