input: clean
	python icosahedral_mesh/icosahedral_gmsh.py icosahedron 2.22 3

clean:
	rm -rf *.vtu *.stat *.detectors *.dat fluidity.* *_state matrixdump* *.pyc log_* *.msh *~* flredecomp.* checkpoint* P4*
