input:
	../../../scripts/interval --dx=0.1 -- 0 12 tube

clean:
	rm -f *.node *.ele *.bound
	rm -f *.vtu *.stat
	rm -f fluidity.err-0 fluidity.log-0
	rm -f matrixdump* velocity* pvf* pressure.d.* cv_rhs*
