input: clean
	# note the -- -50 - we want the z axis with 0 at surface and -50m at depth
	create_aligned_mesh gls-MixedLayer 250 50 -- -50 3 3 25

clean: 
	rm -f  *.msh *.poly *.vtu *.s  *.stat *.log-0 *.err-0 matrixdump* *log *err
