input:	clean
#	cp src/MMS_A.msh .
#	cp src/MMS_B.msh .
#	cp src/MMS_C.msh .
#	cp src/MMS_D.msh .
#	../../debug/bin/periodise MMS_A.flml
#	../../debug/bin/periodise MMS_B.flml
#	../../debug/bin/periodise MMS_C.flml
#	../../debug/bin/periodise MMS_D.flml

clean:
#	rm -f *.vtu *.stat *.s *.log *.node *.ele *.edge *checkpoint*
