input: clean
	gmsh -2 src/square.geo

clean:
	rm -rf src/*.msh *.stat *.vtu *.pvtu *.log-0 *.err-0 *checkpoint *.convergence *.dat nohup.* fluidity* *parallel* *.pyc viscous_fs_drunkensailor_implicit_*
