input: clean

clean:
	rm -f channel channel0 channel.fld
	rm -f channel.s channel.stat
	rm -f *.d.* *.vtu
	rm -f fluidity.err-0 fluidity.log-0
	rm -f *.ele *.face *.node *.edge *.stat *.halo
	rm -f *.msh *.geo \
	matrixdump matrixdump.info
