input:
	gmsh -2 -o Stommel_gyre.msh src/Stommel_gyre.geo
	gmsh -2 -o Stommel_gyre_A.msh src/Stommel_gyre_A.geo


clean:
	rm -f *.node *.ele *.edge *.msh *.vtu *.log* *.err* *.stat *dump* \
	matrixdump matrixdump.info
