#include <h5partPluginInfo.h>

#if defined(__APPLE__)
#define GetEngineInfo h5part_GetEngineInfo
#endif

// ****************************************************************************
//  Function:  GetEngineInfo
//
//  Purpose:
//    Return a new EnginePluginInfo for the h5part database.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 9 09:51:18 PDT 2006
//
// ****************************************************************************
extern "C" EngineDatabasePluginInfo* GetEngineInfo()
{
    return new h5partEnginePluginInfo;
}

// ****************************************************************************
//  Method: h5partCommonPluginInfo::GetWriter
//
//  Purpose:
//      Sets up a h5part writer.
//
//  Returns:    A h5part writer.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 9 09:51:18 PDT 2006
//
// ****************************************************************************
avtDatabaseWriter *
h5partEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

