input:	clean
	../../scripts/gmsh2triangle src/MMS_A.msh
	../../scripts/gmsh2triangle src/MMS_B.msh
	../../scripts/gmsh2triangle src/MMS_C.msh
	../../scripts/gmsh2triangle src/MMS_D.msh

clean:
	rm -f *.vtu *.stat *.s *.log *.node *.ele *.edge *checkpoint*
