input:	clean
	cp src/MMS_A.msh .
	cp src/MMS_B.msh .
	cp src/MMS_C.msh .
	cp src/MMS_D.msh .

clean:
	rm -f *.vtu *.stat *.s *.log *.node *.ele *.edge *.msh *checkpoint* *.log-0 *.err-0 \
	matrixdump matrixdump.info
