#!/usr/bin/env python
from optparse import OptionParser
import sys

#####################################################################
# Script starts here.
optparser=OptionParser(usage='usage: %prog [options]',
                       add_help_option=True,
                       description="""Generate the mesh files for a given"""+
		       """number of layers of elements in the channel.""")

(options, argv) = optparser.parse_args()

sys.path.append(".")

import channel_viscous

layerlist = [5,10,20,50,100]
for layers in layerlist:
    channel_viscous.generate_meshfile("channel"+str(layers),layers)
