// ************************************************************************* //
//  File: H5PartRandomSampleEnginePluginInfo.C
// ************************************************************************* //

#include <H5PartRandomSamplePluginInfo.h>
#include <avtH5PartRandomSampleFilter.h>

#if defined(__APPLE__)
#define GetEngineInfo H5PartRandomSample_GetEngineInfo
#endif

// ****************************************************************************
//  Function:  GetEngineInfo
//
//  Purpose:
//    Return a new EnginePluginInfo for the H5PartRandomSample operator.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:26:55 PDT 2006
//
// ****************************************************************************
extern "C" EngineOperatorPluginInfo* GetEngineInfo()
{
    return new H5PartRandomSampleEnginePluginInfo;
}

// ****************************************************************************
//  Method: H5PartRandomSampleEnginePluginInfo::AllocAvtPluginFilter
//
//  Purpose:
//    Return a pointer to a newly allocated avtPluginFilter.
//
//  Returns:    A pointer to the newly allocated avtPluginFilter.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 16 10:26:55 PDT 2006
//
// ****************************************************************************

avtPluginFilter *
H5PartRandomSampleEnginePluginInfo::AllocAvtPluginFilter()
{
    return new avtH5PartRandomSampleFilter;
}
