input: clean
	triangle2gmsh first_timestep_adapted_mesh

clean:
	rm -rf *.stat first_timestep_adapted_mesh.msh adapted_mesh_*.vtu water_collapse_*.vtu *checkpoint* *convergence* *.log-0 *.err-0
	rm -rf valgrind.out
	rm -rf fluidity.log-0 fluidity.err-0
