# This file was *autogenerated* from the file sol.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
t = var('t')
x = var('x')
c = var('c')
k = var('k')
g = var('g') # gravity
H = var('H') # depth
a = _sage_const_0 
b = _sage_const_1 

eta = -c * sin(k*x+t)
u = c * sin(k*x+t)

print "u: ", u
print "eta: ", eta
print "mom source: ", g*diff(eta, x) + diff(u, t)
print "cont source: ", diff(eta, t) + diff(H*u, x)
