input: 	clean
	gmsh -3 src/cube.geo -algo front3d -o cube.msh

clean:
	rm -rf fluidity.* cube.msh coarsenp* coarsen_* coarsen.stat adapted_state* metric_input* gradation_metric* bounding_box*
	rm -rf matrixdump*
