input: clean
	#gmsh -3 -o cube-12.msh src/cube_12.geo
	#gmsh -3 -o cube-24.msh src/cube_24.geo
	#gmsh -3 -o cube-48.msh src/cube_48.geo
	#../../bin/gmsh2triangle cube-12.msh
	#../../bin/gmsh2triangle cube-24.msh
	#../../bin/gmsh2triangle cube-48.msh
	#../../bin/fldecomp -n 4 -f cube-48

clean:
	#rm -f *.ele *.face *.node
