# This file was *autogenerated* from the file source_terms.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
x = var('x')
y = var('y')
t = var('t')
h = var('h')
g = var('g')
H = var('d0')

eta = -h*sin(_sage_const_2 *pi*(x+t)) - h*sin(_sage_const_2 *pi*(y+t))
u_x = h*sin(_sage_const_2 *pi*(x+t)) 
u_y = h*sin(_sage_const_2 *pi*(y+t))

u_x_src = g*diff(eta, x) + diff(u_x, t)
u_y_src = g*diff(eta, y) + diff(u_y, t)
eta_src = diff(eta, t) + diff(H*u_x, x) + diff(H*u_y, y)

print "u_x: ", u_x.subs(h=_sage_const_1 )
print "u_y: ", u_y.subs(h=_sage_const_1 )
print "eta: ", eta.subs(h=_sage_const_1 )

print "u_x src: ", u_x_src.subs(h=_sage_const_1 )
print "u_y src: ", u_y_src.subs(h=_sage_const_1 )
print "eta_src: ", eta_src.subs(h=_sage_const_1 )
