input: clean
	cp src/column.msh .

clean:
	rm -f *.halo *.face *.ele *.edge *.node *.msh *.poly *.pvtu *.vtu *.s *.d.1 *.stat \
	matrixdump matrixdump.info
	rm -rf photosynthetic_radiation_? *flredecomp*
