SWML=rossby_wave.swml.template
SIMULATION=rossby
PDEGREE=1
UDEGREE=2
VDEGREE=2
CONSTRAINT=RT
OUTPUTMESH=PressureMesh

include sw_common/common.mk

input:	clean channel_mesh_convergence_quads rossby_swml
