#!/usr/bin/env python

from optparse import OptionParser
import re
import sys
import os.path

#####################################################################
# Script starts here.
optparser=OptionParser(usage='usage: %prog [options] <filename>',
                       add_help_option=True,
                       description="""This takes a Gmsh 2.0 .msh ascii file """ + 
                       """and produces .node, .ele and .edge or .face files.""")

optparser.add_option("--2D", "--2d", "-2",
                  help="discard 3rd coordinate of node positions",
		     action="store_const", const=2, dest="dim", default=3)

(options, argv) = optparser.parse_args()

if len(argv)<1:
    optparser.print_help()
    sys.exit(1)

if argv[0][-4:]!=".msh":
    sys.stderr.write("Mesh filename must end in .msh\n")
    optparser.print_help()
    sys.exit(1)
    

basename=os.path.basename(argv[0][:-4])

mshfile=file(argv[0], 'r')

# Header section
assert(mshfile.readline().strip()=="$MeshFormat")
assert(mshfile.readline().strip()in["2 0 8", "2.1 0 8", "2.2 0 8"])
assert(mshfile.readline().strip()=="$EndMeshFormat")

# Nodes section
while mshfile.readline().strip() !="$Nodes":
    pass
nodecount=int(mshfile.readline())

dim=options.dim
nodefile=file(basename+".node", 'w')
nodefile.write(`nodecount`+" "+`dim`+" 0 0\n")

gmsh_node_map = {}
for i in range(nodecount):
    # Node syntax
    line = mshfile.readline().split()
    gmsh_node = line[0] # the node number that gmsh has assigned, which might
                        # not be consecutive
    gmsh_node_map[gmsh_node] = str(i+1)
    nodefile.write(" ".join( [str(i+1)] + line[1:dim+1] )+"\n")

nodefile.write("# Produced by: "+" ".join(argv)+"\n")
nodefile.close()

assert(mshfile.readline().strip()=="$EndNodes")

# Elements section
assert(mshfile.readline().strip()=="$Elements")
elementcount=int(mshfile.readline())

# Now loop over the elements placing them in the appropriate buckets.
edges=[]
triangles=[]
tets=[]
quads=[]
hexes=[]

for i in range(elementcount):
    
    element=mshfile.readline().split()

    if (element[1]=="1"):
        edges.append(element[-2:]+[element[3]])
    elif (element[1]=="2"):
        triangles.append(element[-3:]+[element[3]])
    elif (element[1]=="3"):
        quads.append(element[-4:]+[element[3]])
    elif (element[1]=="4"):
        tets.append(element[-4:]+[element[3]])
    elif (element[1]=="5"):
        hexes.append(element[-8:]+[element[3]])
    elif(element[1]=="15"):
        # Ignore point elements
        pass
    else:
        sys.stderr.write("Unknown element type "+`element[1]`+'\n')
        sys.exit(1)

if len(tets) > 0:
  if len(hexes) > 0:
    sys.stderr.write("Warning: Mixed tet/hex mesh encountered - discarding hexes")
  if len(quads) > 0:
    sys.stderr.write("Warning: Mixed tet/quad mesh encountered - discarding quads")
elif len(triangles) > 0:
  if len(hexes) > 0:
    sys.stderr.write("Warning: Mixed triangle/hex mesh encountered - discarding hexes")
  if len(quads) > 0:
    sys.stderr.write("Warning: Mixed triangle/quad mesh encountered - discarding quads")

if len(tets)>0:
    dim=3
    loc=4
    node_order=[1, 2, 3, 4]
    elements=tets
    faces=triangles
    elefile=file(basename+".ele", "w")
    facefile=file(basename+".face", "w")

elif len(triangles)>0:
    dim=2
    loc=3
    node_order=[1, 2, 3]
    elements=triangles
    faces=edges
    elefile=file(basename+".ele", "w")
    facefile=file(basename+".edge", "w")

elif len(hexes)>0:
    dim=3
    loc=8
    node_order=[1, 2, 4, 3, 5, 6, 8, 7]
    elements=hexes
    faces=quads
    elefile=file(basename+".ele", "w")
    facefile=file(basename+".face", "w")

elif len(quads)>0:
    dim=2
    loc=4
    node_order=[1, 2, 4, 3]   # don't really know if this is right
    elements=quads
    faces=edges
    elefile=file(basename+".ele", "w")
    facefile=file(basename+".edge", "w")

else:
    sys.stderr.write("Unable to determine dimension of problem\n")
    sys.exit(1)


# Output ele file
elefile.write(`len(elements)`+" "+`loc`+" 1\n")

for i, element in enumerate(elements):
    elefile.write(`i+1`+" ")
    for j in node_order:
        elefile.write(" ".join([gmsh_node_map[x] for x in element[j-1:j]])+" ")
    elefile.write(" ".join(element[-1:]))
    elefile.write(" "+"\n")

elefile.write("# Produced by: "+" ".join(sys.argv)+"\n")
elefile.close()

# Output problem file
facefile.write(`len(faces)`+" 1\n")

for i,face in enumerate(faces):
    facefile.write(`i+1`+" "+" ".join(face)+"\n")

facefile.write("# Produced by: "+" ".join(sys.argv)+"\n")
facefile.close()

