#!/usr/bin/env python
import re
import glob

# File header
header="""
subroutine register_diagnostics

"""
footer="""
end subroutine register_diagnostics
"""

outfile=file("preprocessor/register_diagnostics.F90", "w")

outfile.write(header)

# List of fortran source files.
fortran_files=glob.glob("*/*.F")+glob.glob("*/*.F90")

module_re=re.compile(r"^\s*module\s+(\w+)\s*$",re.IGNORECASE|re.MULTILINE)

module_list=[]

for filename in fortran_files:
    
    fortran=file(filename,"r").read()

    modules=module_re.findall(fortran)

    for module in modules:

        if re.search(r"^\s*subroutine\s+"+module+"_register_diagnostic\s*$",\
                     fortran,\
                     re.IGNORECASE|re.MULTILINE):
            module_list.append(module)

for module in module_list:

        outfile.write("  use "+module+", only: "+module+"_register_diagnostic\n")

# Ensure that the subroutine is legal in the trivial case.
outfile.write("""
   continue
   """)

for module in module_list:

    outfile.write("  call "+module+"_register_diagnostic\n")

outfile.write(footer)
