#!/bin/bash

for F in A B C
do
    echo creating set $F with n_ele=$n	

    cp MMS_X.flml MMS_$F.flml 
    sed s/MMS_X/MMS_$F/ MMS_$F.flml > MMS_$F.flml.cp
done

echo setting flml timestep values

sed s/999.9/0.16/ MMS_A.flml.cp > MMS_A.flml
rm MMS_A.flml.cp
sed s/999.9/0.08/ MMS_B.flml.cp > MMS_B.flml
rm MMS_B.flml.cp
sed s/999.9/0.04/ MMS_C.flml.cp > MMS_C.flml
rm MMS_C.flml.cp
