clean:
	rm -f test_triangle_precision_out*
	rm -f cube_unstructured.face cube_unstructured.ele cube_unstructured.msh cube_unstructured.node
	rm -f cube_prismatic.face cube_prismatic.ele cube_prismatic.msh cube_prismatic.node
	rm -f matrix2.mm test_halo_io_out_0.halo test_stream_io_out
	rm -f adapt_?.vtu bound_field_out.vtu bounding_?.vtu cg_interpolation_?.vtu cubic_interpolation_?.vtu curl_out_?.vtu cylinder_hessian_?.vtu dg_interpolation_?.vtu differentiate_field_?.vtu div_out_?.vtu empty_populate_state.vtu laplacian_grid_2.vtu layered_mesh_?.vtu linear_interpolation_?.vtu metric_based_extrusion_?.vtu pseudo_supermesh_2.vtu quadratic_interpolation_?.vtu sam_integration_?.vtu solenoidal_interpolation_?.vtu strain_rate_out_?.vtu tensor_second_invariant_out_?.vtu test_adapt_mesh_out.vtu test_adapt_state_3d_out_?.vtu test_adapt_state_unittest_out_?.vtu test_potential_vorticity_out.vtu test_relative_potential_vorticity_out.vtu test_u_dot_nabla_out_?.vtu test_vtk_precision_out.vtu vfield_adapt_?.vtu z_mesh_?.vtu
