clean:
	rm -f test_triangle_precision_out*
	rm -f cube_unstructured.face cube_unstructured.ele cube_unstructured.msh cube_unstructured.node
	rm -f cube_prismatic.face cube_prismatic.ele cube_prismatic.msh cube_prismatic.node
	rm -f matrix2.mm test_halo_io_out_0.halo test_stream_io_out
