input: clean
	gmsh -2 -bin -o mesh/sb_mesh.msh mesh/sb_mesh.geo

clean:
	rm -r -f Benchmark_Case_1a* *.pvtu *.vtu *.stat *.detectors *.dat fluidity.* *_state matrixdump* log_* *.pyc *~* flredecomp* Parallel*
