input:
	gmsh -3 mesh_A.geo
	../../../scripts/gmsh2triangle mesh_A.msh
	gmsh -3 mesh_B.geo
	../../../scripts/gmsh2triangle mesh_B.msh
	gmsh -3 mesh_C.geo
	../../../scripts/gmsh2triangle mesh_C.msh
	gmsh -3 mesh_D.geo
	../../../scripts/gmsh2triangle mesh_D.msh
