#!/usr/bin/env python
import pylab
import channel_viscous
import sys
import numpy

layers=numpy.array(map(int,sys.argv[1:]))

dx=1./layers

error=channel_viscous.retrieve_results(layers)

channel_viscous.plot_results(dx,error)

pylab.show()



