#!/usr/bin/env python
import pylab
import channel_viscous
import sys
import numpy

def usage():
    print """plot_data <layers>

    <layers> is a space-separated list of layer counts."""
    

try:
    layers=numpy.array(map(int,sys.argv[1:]))
except:
    usage()
    sys.exit(1)

if len(layers)==0:
    usage()
    sys.exit(1)


dx=1./layers

error=channel_viscous.retrieve_results(layers)

channel_viscous.plot_results(dx,error)

pylab.show()



