input: clean
	../../scripts/gmsh2triangle --2d src/2element_square.msh

clean:
	rm -rf *.vtu 2element_square.node 2element_square.ele 2element_square.face *.convergence *checkpoint* fluidity.err-* fluidity.log-*
