input: clean
	cp src/2element_square.msh .

clean:
	rm -rf *.vtu 2element_square.node 2element_square.ele 2element_square.face *.convergence *checkpoint* fluidity.err-* fluidity.log-* 2element_square.edge lagrange_tracer.detectors lagrange_tracer.detectors.dat lagrange_tracer.stat \
	matrixdump matrixdump.info
