#include <h5partPluginInfo.h>

#if defined(__APPLE__)
#define GetMDServerInfo h5part_GetMDServerInfo
#endif

// ****************************************************************************
//  Function:  GetMDServerInfo
//
//  Purpose:
//    Return a new MDServerPluginInfo for the h5part database.
//
//  Programmer: cristina -- generated by xml2info
//  Creation:   Thu Mar 9 09:51:18 PDT 2006
//
// ****************************************************************************
extern "C" MDServerDatabasePluginInfo* GetMDServerInfo()
{
    return new h5partMDServerPluginInfo;
}

// this makes compilers happy... remove if we ever have functions here
void h5partMDServerPluginInfo::dummy()
{
}
