meshes:
	gmsh -2 sphere_A.geo
	../../../scripts/gmsh2triangle sphere_A.msh
	gmsh -2 sphere_B.geo
	../../../scripts/gmsh2triangle sphere_B.msh
	gmsh -2 sphere_C.geo
	../../../scripts/gmsh2triangle sphere_C.msh
