#!/usr/bin/env python3
from optparse import OptionParser
import sys

#####################################################################
# Script starts here.
optparser=OptionParser(usage='usage: %prog [options] <layers>',
                       add_help_option=True,
                       description="""Generate the mesh files for a given"""+
		       """typical edge length 1.0/layers.""")

(options, argv) = optparser.parse_args()

#try:
layers=float(argv[0])
dx = 1.0/layers
print('dx = ',dx)
#except:
#    optparser.print_help()
#    sys.exit(1)

sys.path.append(".")

import cdg3d

cdg3d.generate_meshfile("box",layers)
