input:	clean
	cp src/MMS_A.msh .
	cp src/MMS_B.msh .
	cp src/MMS_C.msh .
	cp src/MMS_D.msh .
	cp src/MMS_E.msh .
	#cp src/MMS_F.msh .

clean:
	rm -f *.vtu *.stat *.log *.node *.ele *.edge *.msh *checkpoint* *.convergence \
	matrixdump matrixdump.info
