input:	clean
	../../bin/gmsh2triangle --2d src/MMS_A.msh
	../../bin/gmsh2triangle --2d src/MMS_B.msh
	../../bin/gmsh2triangle --2d src/MMS_C.msh
	../../bin/gmsh2triangle --2d src/MMS_D.msh
	../../bin/gmsh2triangle --2d src/MMS_E.msh
	#../../bin/gmsh2triangle --2d src/MMS_F.msh

clean:
	rm -f *.vtu *.stat *.log *.node *.ele *.edge *checkpoint* *.convergence
