#!/bin/bash

n=8
for F in A B C
do
    echo creating set $F with n_ele=$n	

    cp MMS_X.flml MMS_$F.flml 
    $SED s/MMS_X/MMS_$F/ MMS_$F.flml > MMS_$F.flml.cp

    $SED s/XX/$n/ src/MMS_X.geo > src/MMS_$F.geo	

    n=$((n*2))
done

echo setting flml timestep values

# Remember, we have to double the Smagorinsky
# coefficient each time to compensate for the
# halving of the element length. Otherwise,
# the Source term will no longer be valid
# as it always uses the element area from the MMS_A run.
$SED s/999.9/0.125/ MMS_A.flml.cp > MMS_A.flml.cp2
$SED s/888.8/0.1/ MMS_A.flml.cp2 > MMS_A.flml
rm MMS_A.flml.cp*
$SED s/999.9/0.0625/ MMS_B.flml.cp > MMS_B.flml.cp2
$SED s/888.8/0.2/ MMS_B.flml.cp2 > MMS_B.flml
rm MMS_B.flml.cp*
$SED s/999.9/0.03125/ MMS_C.flml.cp > MMS_C.flml.cp2
$SED s/888.8/0.4/ MMS_C.flml.cp2 > MMS_C.flml
rm MMS_C.flml.cp*
