input: clean
	triangle2gmsh coarse

clean:
	rm -rf coarse.msh
	rm -rf *.vtu *.pvtu
	rm -rf fluidity.* *.stat
	rm -rf *_[0-9]*.*
	rm -rf matrixdump*
	rm -rf *flredecomp*
	rm -rf baroclinic_gyre_unstructured_res2_p1dgp2_cgsupg_NoSlipBottom_BR_[0-9]
	rm -rf baroclinic_gyre_unstructured_res2_p1dgp2_cgsupg_NoSlipBottom_BR_[0-9][0-9]
